### ISSUE TITLE
options incomplete?

### ISSUE THREAD

**Issue by qingchuwudi** [gotthardp/gen_coap#2]
Options in coap_message_parser.erl  are less than [rfc7252][1] on page 53. Why?

[1]: http://tools.ietf.org/pdf/rfc7252.pdf "rfc7252"

**Comment by gotthardp** [comment]
Because I was lazy. Those options are not used anywhere in the implementation and there are provisions for handling unknown options, so I thought that maybe the parser doesn't need to implement them explicitly for the time being.

I fixed that. The parser now explicitly supports all options although they are still not used anywhere in the implementation. There are still features (proxying and uri query) that are not implemented.
